"""Generate ROUTE_MAP.json for Flutter projects.

Extracts all named routes, their screen bindings, and navigation patterns.
"""

import re
import json
from pathlib import Path
from collections import defaultdict

ROUTE_CONST = re.compile(r"static\s+const\s+(\w+)\s*=\s*['\"]([^'\"]+)['\"]")
GET_PAGE = re.compile(
    r"GetPage\s*\(\s*name\s*:\s*['\"]?(\w+\.)?(\w+)['\"]?\s*,"
    r"\s*page\s*:\s*\(\)\s*=>\s*(\w+)",
    re.DOTALL
)
ROUTE_USAGE = re.compile(r"(?:Get\.toNamed|Get\.offNamed|Get\.offAllNamed|Navigator\.pushNamed)\s*\(\s*['\"]?(\w+\.)?(\w+)['\"]?")
GO_PATTERN = re.compile(r"(?:Get\.to|Get\.off|Navigator\.push)\s*\(\s*\(\)\s*=>\s*(\w+)")


def generate(project_root: str | Path, output_path: str | Path = None) -> Path:
    project_root = Path(project_root).resolve()
    lib_dir = project_root / "lib"

    if output_path is None:
        output_path = project_root / "docs" / "ROUTE_MAP.json"

    routes = {}
    route_usages = defaultdict(list)

    # Phase 1: Find route constants
    for dart_file in sorted(lib_dir.rglob("*.dart")):
        if 'route' not in dart_file.name.lower() and 'page' not in dart_file.name.lower():
            continue
        try:
            content = dart_file.read_text(errors='ignore')
        except Exception:
            continue

        rel_path = str(dart_file.relative_to(project_root))

        for match in ROUTE_CONST.finditer(content):
            name = match.group(1)
            path = match.group(2)
            routes[name] = {
                "name": name,
                "path": path,
                "defined_in": rel_path,
            }

    # Phase 2: Find GetPage bindings (route -> screen)
    for dart_file in sorted(lib_dir.rglob("*.dart")):
        try:
            content = dart_file.read_text(errors='ignore')
        except Exception:
            continue

        if 'GetPage' not in content:
            continue

        # Simpler pattern: find GetPage with name and page params
        pages = re.findall(
            r'GetPage\s*\([^)]*name\s*:\s*(?:AppRoutes\.)?(\w+)[^)]*page\s*:\s*\(\)\s*=>\s*(\w+)',
            content, re.DOTALL
        )
        for route_name, screen_class in pages:
            if route_name in routes:
                routes[route_name]["screen"] = screen_class
            else:
                routes[route_name] = {
                    "name": route_name,
                    "path": f"/{route_name}",
                    "screen": screen_class,
                    "defined_in": str(dart_file.relative_to(project_root)),
                }

    # Phase 3: Find route navigation usage
    for dart_file in sorted(lib_dir.rglob("*.dart")):
        try:
            content = dart_file.read_text(errors='ignore')
        except Exception:
            continue

        parts = dart_file.relative_to(lib_dir).parts
        module = parts[0] if len(parts) > 1 else "root"

        for match in ROUTE_USAGE.finditer(content):
            route_ref = match.group(2)
            route_usages[route_ref].append(module)

    # Merge usage
    for name, modules in route_usages.items():
        if name in routes:
            routes[name]["navigated_from"] = sorted(set(modules))

    output = {
        "_meta": {
            "generated": "auto-generated by TokenSaver flutter_route_map.py",
            "total_routes": len(routes),
            "with_screen_binding": sum(1 for r in routes.values() if "screen" in r),
        },
        "routes": {k: v for k, v in sorted(routes.items())},
    }

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(json.dumps(output, indent=2))
    return Path(output_path)


if __name__ == "__main__":
    import sys
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    out = generate(root)
    data = json.loads(out.read_text())
    print(f"Generated {out} ({out.stat().st_size // 1024}KB)")
    print(f"  {data['_meta']['total_routes']} routes, {data['_meta']['with_screen_binding']} with screen bindings")
