"""Generate API_MANIFEST.json for Flutter projects.

Scans all Dart files for API endpoint URLs, HTTP methods, and maps them
to their modules and data models.
"""

import re
import json
from pathlib import Path
from collections import defaultdict

# Patterns for API calls
URL_PATTERNS = [
    # String literals with /api/
    re.compile(r'''["']([^"']*\/api\/[^"']+)["']'''),
    # Interpolated strings with /api/
    re.compile(r'''["']\$\{?\w+\}?([^"']*\/api\/[^"']+)["']'''),
    # Variable assignments with URL paths
    re.compile(r'''(?:url|endpoint|path|baseUrl)\s*[:=]\s*["']([^"']+)["']'''),
]

HTTP_METHOD_PATTERN = re.compile(
    r'(?:dio|http|client)\s*\.\s*(get|post|put|delete|patch)\s*[<(]',
    re.IGNORECASE
)

RESPONSE_MODEL_PATTERN = re.compile(
    r'fromJson|fromMap|\.map\(\s*\(.*?\)\s*=>\s*(\w+)\.from'
)


def generate(project_root: str | Path, output_path: str | Path = None) -> Path:
    project_root = Path(project_root).resolve()
    lib_dir = project_root / "lib"

    if output_path is None:
        output_path = project_root / "docs" / "API_MANIFEST.json"

    endpoints = []
    url_files = defaultdict(list)

    for dart_file in sorted(lib_dir.rglob("*.dart")):
        if dart_file.name.endswith(('.g.dart', '.freezed.dart')):
            continue

        try:
            content = dart_file.read_text(errors='ignore')
        except Exception:
            continue

        rel_path = str(dart_file.relative_to(project_root))
        # Detect module
        parts = dart_file.relative_to(lib_dir).parts
        module = parts[0] if len(parts) > 1 else "root"

        # Find URLs
        urls_found = set()
        for pattern in URL_PATTERNS:
            for match in pattern.finditer(content):
                url = match.group(1) if match.lastindex else match.group(0)
                url = url.strip("'\"")
                if '/api/' in url or url.startswith('/'):
                    urls_found.add(url)

        # Find HTTP methods in this file
        methods = set(m.upper() for m in HTTP_METHOD_PATTERN.findall(content))

        for url in urls_found:
            # Clean URL
            clean_url = _clean_url(url)
            if not clean_url:
                continue

            entry = {
                "url": clean_url,
                "methods": sorted(methods) if methods else ["GET"],
                "module": module,
                "file": rel_path,
            }

            # Try to find response model
            models = RESPONSE_MODEL_PATTERN.findall(content)
            if models:
                entry["response_models"] = sorted(set(models))[:3]

            endpoints.append(entry)

    # Deduplicate by URL
    seen = {}
    for ep in endpoints:
        key = ep["url"]
        if key not in seen:
            seen[key] = ep
        else:
            # Merge methods and modules
            seen[key]["methods"] = sorted(set(seen[key]["methods"] + ep["methods"]))
            if ep["module"] != seen[key]["module"]:
                if "other_modules" not in seen[key]:
                    seen[key]["other_modules"] = []
                seen[key]["other_modules"].append(ep["module"])

    deduped = sorted(seen.values(), key=lambda x: x["url"])

    output = {
        "_meta": {
            "generated": "auto-generated by TokenSaver flutter_api_manifest.py",
            "total_endpoints": len(deduped),
            "modules_with_apis": len(set(ep["module"] for ep in deduped)),
        },
        "endpoints": deduped,
    }

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(json.dumps(output, indent=2))
    return Path(output_path)


def _clean_url(url: str) -> str:
    """Normalize a URL to its path pattern."""
    # Remove host
    url = re.sub(r'https?://[^/]+', '', url)
    # Remove query params
    url = url.split('?')[0]
    # Remove trailing slash
    url = url.rstrip('/')
    # Skip empty or too short
    if len(url) < 3:
        return ""
    return url


if __name__ == "__main__":
    import sys
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    out = generate(root)
    data = json.loads(out.read_text())
    print(f"Generated {out} ({out.stat().st_size // 1024}KB)")
    print(f"  {data['_meta']['total_endpoints']} endpoints across {data['_meta']['modules_with_apis']} modules")
