"""Generate WIDGET_CATALOG.json for Flutter projects.

Scans common/widgets/ and shared components, extracting widget names,
constructor params, and usage across modules.
"""

import re
import json
from pathlib import Path
from collections import defaultdict

WIDGET_CLASS = re.compile(
    r'class\s+(\w+)\s+extends\s+(Stateless|Stateful)Widget'
)
CONSTRUCTOR_PARAMS = re.compile(
    r'(?:const\s+)?(\w+)\s*\(\s*\{([^}]*)\}\s*\)',
    re.DOTALL
)
PARAM_LINE = re.compile(
    r'(?:required\s+)?(?:this\.)?(\w+)\s*(?:,|$)'
)
IMPORT_WIDGET = re.compile(
    r"import\s+'[^']*common/(?:widgets|components)/([^']+)'"
)


def generate(project_root: str | Path, output_path: str | Path = None) -> Path:
    project_root = Path(project_root).resolve()
    lib_dir = project_root / "lib"
    common_dir = lib_dir / "common"

    if output_path is None:
        output_path = project_root / "docs" / "WIDGET_CATALOG.json"

    widgets = {}

    # Scan common/widgets and common/components
    for subdir in ['widgets', 'components', 'shared']:
        scan_dir = common_dir / subdir
        if not scan_dir.exists():
            continue

        for dart_file in sorted(scan_dir.rglob("*.dart")):
            if dart_file.name.endswith(('.g.dart', '.freezed.dart')):
                continue

            try:
                content = dart_file.read_text(errors='ignore')
            except Exception:
                continue

            rel_path = str(dart_file.relative_to(project_root))

            for match in WIDGET_CLASS.finditer(content):
                name = match.group(1)
                widget_type = match.group(2) + "Widget"

                # Extract constructor params
                params = _extract_params(content, name)

                widgets[name] = {
                    "name": name,
                    "type": widget_type,
                    "file": rel_path,
                    "params": params,
                }

    # Scan usage across modules
    widget_names = set(widgets.keys())
    if widget_names:
        usage = defaultdict(set)
        for dart_file in lib_dir.rglob("*.dart"):
            if dart_file.name.endswith(('.g.dart', '.freezed.dart')):
                continue
            try:
                content = dart_file.read_text(errors='ignore')
            except Exception:
                continue

            parts = dart_file.relative_to(lib_dir).parts
            module = parts[0] if len(parts) > 1 else "root"

            for wname in widget_names:
                if wname in content and module != "common":
                    usage[wname].add(module)

        for wname, modules in usage.items():
            if wname in widgets:
                widgets[wname]["used_in"] = sorted(modules)
                widgets[wname]["usage_count"] = len(modules)

    output = {
        "_meta": {
            "generated": "auto-generated by TokenSaver flutter_widget_catalog.py",
            "total_widgets": len(widgets),
            "most_reused": sorted(
                [(w["name"], w.get("usage_count", 0)) for w in widgets.values()],
                key=lambda x: x[1], reverse=True
            )[:10],
        },
        "widgets": {k: v for k, v in sorted(widgets.items())},
    }

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(json.dumps(output, indent=2))
    return Path(output_path)


def _extract_params(content: str, class_name: str) -> list[str]:
    """Extract constructor parameter names for a widget class."""
    # Find the constructor
    pattern = re.compile(
        rf'(?:const\s+)?{re.escape(class_name)}\s*\(\s*\{{([^}}]*)\}}\s*\)',
        re.DOTALL
    )
    match = pattern.search(content)
    if not match:
        return []

    params_block = match.group(1)
    params = []
    for line in params_block.split(','):
        line = line.strip()
        if not line:
            continue
        # Extract param name (last word before = or end)
        parts = line.split()
        for p in reversed(parts):
            p = p.strip('?,')
            if p and p != 'required' and p != 'this' and not p.startswith('//'):
                if p.startswith('this.'):
                    p = p[5:]
                params.append(p)
                break

    return params[:15]  # Cap


if __name__ == "__main__":
    import sys
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    out = generate(root)
    data = json.loads(out.read_text())
    print(f"Generated {out} ({out.stat().st_size // 1024}KB)")
    print(f"  {data['_meta']['total_widgets']} widgets")
