"""Generate REMOTE_CONFIG_INDEX.json for Flutter projects.

Scans for remote config keys, feature flags, and their usage across modules.
"""

import re
import json
from pathlib import Path
from collections import defaultdict

# Patterns for remote config access
RC_PATTERNS = [
    re.compile(r'''remoteConfig\s*\[\s*["'](\w+)["']\s*\]'''),
    re.compile(r'''getString\s*\(\s*["'](\w+)["']\s*\)'''),
    re.compile(r'''getBool\s*\(\s*["'](\w+)["']\s*\)'''),
    re.compile(r'''getInt\s*\(\s*["'](\w+)["']\s*\)'''),
    re.compile(r'''getDouble\s*\(\s*["'](\w+)["']\s*\)'''),
    re.compile(r'''getValue\s*\(\s*["'](\w+)["']\s*\)'''),
    re.compile(r'''getJson\s*\(\s*["'](\w+)["']\s*\)'''),
    # Common patterns: RemoteConfigService.instance.xxx
    re.compile(r'''(?:remoteConfig|rcService|featureFlag)\w*\.(\w+)'''),
    # Static const keys
    re.compile(r'''static\s+(?:const|final)\s+\w+\s+(\w+Key)\s*=\s*["'](\w+)["']'''),
]

# Feature flag patterns
FLAG_PATTERNS = [
    re.compile(r'''(?:is|enable|show|hide|flag|feature)\w*\s*[:=]\s*(?:remoteConfig|rc)\w*\[["'](\w+)["']\]''', re.IGNORECASE),
    re.compile(r'''(?:isEnabled|isVisible|shouldShow)\(\s*["'](\w+)["']\s*\)'''),
]


def generate(project_root: str | Path, output_path: str | Path = None) -> Path:
    project_root = Path(project_root).resolve()
    lib_dir = project_root / "lib"

    if output_path is None:
        output_path = project_root / "docs" / "REMOTE_CONFIG_INDEX.json"

    config_keys = defaultdict(lambda: {"files": [], "modules": set(), "type": "unknown"})

    for dart_file in sorted(lib_dir.rglob("*.dart")):
        if dart_file.name.endswith(('.g.dart', '.freezed.dart')):
            continue

        try:
            content = dart_file.read_text(errors='ignore')
        except Exception:
            continue

        rel_path = str(dart_file.relative_to(project_root))
        parts = dart_file.relative_to(lib_dir).parts
        module = parts[0] if len(parts) > 1 else "root"

        # Find config keys
        for pattern in RC_PATTERNS:
            for match in pattern.finditer(content):
                key = match.group(1)
                # Skip common false positives
                if key in ('this', 'super', 'context', 'state', 'widget', 'value'):
                    continue
                if len(key) < 3:
                    continue
                config_keys[key]["files"].append(rel_path)
                config_keys[key]["modules"].add(module)

        # Detect type from context
        for line in content.split('\n'):
            if 'getBool' in line:
                for pattern in RC_PATTERNS:
                    for m in pattern.finditer(line):
                        config_keys[m.group(1)]["type"] = "bool"
            elif 'getString' in line:
                for pattern in RC_PATTERNS:
                    for m in pattern.finditer(line):
                        config_keys[m.group(1)]["type"] = "string"
            elif 'getInt' in line:
                for pattern in RC_PATTERNS:
                    for m in pattern.finditer(line):
                        config_keys[m.group(1)]["type"] = "int"
            elif 'getJson' in line:
                for pattern in RC_PATTERNS:
                    for m in pattern.finditer(line):
                        config_keys[m.group(1)]["type"] = "json"

    # Convert sets to lists for JSON
    entries = {}
    for key, data in sorted(config_keys.items()):
        entries[key] = {
            "key": key,
            "type": data["type"],
            "modules": sorted(data["modules"]),
            "used_in_files": len(data["files"]),
        }

    output = {
        "_meta": {
            "generated": "auto-generated by TokenSaver flutter_remote_config.py",
            "total_keys": len(entries),
            "modules_using_config": len(set(
                m for e in entries.values() for m in e["modules"]
            )),
        },
        "config_keys": entries,
    }

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(json.dumps(output, indent=2))
    return Path(output_path)


if __name__ == "__main__":
    import sys
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    out = generate(root)
    data = json.loads(out.read_text())
    print(f"Generated {out} ({out.stat().st_size // 1024}KB)")
    print(f"  {data['_meta']['total_keys']} config keys across {data['_meta']['modules_using_config']} modules")
