"""Generate MODULE_MANIFEST.json for Flutter projects.

Scans lib/ for feature modules and extracts:
- Screens/pages, BLoCs/Cubits, repositories, models, services
- File counts, test coverage estimate
- Inter-module dependencies
"""

import re
import json
import os
from pathlib import Path
from collections import defaultdict

# Patterns to detect classes
SCREEN_PATTERN = re.compile(r'class\s+(\w+(?:Screen|Page|View))\s+extends\s+\w+')
BLOC_PATTERN = re.compile(r'class\s+(\w+(?:Bloc|Cubit|Controller|Provider))\s+extends\s+\w+')
REPO_PATTERN = re.compile(r'class\s+(\w+Repository(?:Impl)?)\s+(?:extends|implements)\s+\w+')
MODEL_PATTERN = re.compile(r'class\s+(\w+(?:Model|Entity|Dto|Response|Request))\s+')
SERVICE_PATTERN = re.compile(r'class\s+(\w+Service)\s+')
WIDGET_PATTERN = re.compile(r'class\s+(\w+(?:Widget|Card|Tile|Item|Button|Dialog))\s+extends\s+\w+')
IMPORT_PATTERN = re.compile(r"import\s+'package:[\w_]+/(\w+)/")


def generate(project_root: str | Path, output_path: str | Path = None) -> Path:
    project_root = Path(project_root).resolve()
    lib_dir = project_root / "lib"
    test_dir = project_root / "test"

    if not lib_dir.exists():
        raise FileNotFoundError(f"No lib/ directory found in {project_root}")

    if output_path is None:
        output_path = project_root / "docs" / "MODULE_MANIFEST.json"

    # Discover modules (top-level directories in lib/)
    modules = {}
    skip = {'routes', 'config', 'main.dart', 'generated', 'l10n'}

    for entry in sorted(lib_dir.iterdir()):
        if entry.is_file():
            continue
        if entry.name in skip or entry.name.startswith('.'):
            continue

        module_name = entry.name
        module_data = _scan_module(entry, module_name, test_dir)
        if module_data["file_count"] > 0:
            modules[module_name] = module_data

    # Build output
    output = {
        "_meta": {
            "generated": "auto-generated by TokenSaver flutter_module_manifest.py",
            "total_modules": len(modules),
            "total_files": sum(m["file_count"] for m in modules.values()),
            "total_lines": sum(m["line_count"] for m in modules.values()),
        },
        "modules": modules,
    }

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(json.dumps(output, indent=2))
    return Path(output_path)


def _scan_module(module_dir: Path, module_name: str, test_dir: Path) -> dict:
    screens = []
    blocs = []
    repos = []
    models = []
    services = []
    widgets = []
    imports = set()
    file_count = 0
    line_count = 0
    layers = set()

    for dart_file in module_dir.rglob("*.dart"):
        if dart_file.name.endswith('.g.dart') or dart_file.name.endswith('.freezed.dart'):
            continue

        file_count += 1
        try:
            content = dart_file.read_text(errors='ignore')
            lines = content.count('\n')
            line_count += lines
        except Exception:
            continue

        # Detect layer
        rel = str(dart_file.relative_to(module_dir))
        for layer in ['presentation', 'application', 'domain', 'infrastructure', 'common']:
            if layer in rel:
                layers.add(layer)

        # Extract classes
        screens.extend(SCREEN_PATTERN.findall(content))
        blocs.extend(BLOC_PATTERN.findall(content))
        repos.extend(REPO_PATTERN.findall(content))
        models.extend(MODEL_PATTERN.findall(content))
        services.extend(SERVICE_PATTERN.findall(content))
        widgets.extend(WIDGET_PATTERN.findall(content))

        # Extract cross-module imports
        for m in IMPORT_PATTERN.findall(content):
            if m != module_name:
                imports.add(m)

    # Test coverage estimate
    test_module_dir = test_dir / module_name
    test_files = len(list(test_module_dir.rglob("*.dart"))) if test_module_dir.exists() else 0

    return {
        "file_count": file_count,
        "line_count": line_count,
        "layers": sorted(layers),
        "screens": sorted(set(screens)),
        "blocs": sorted(set(blocs)),
        "repositories": sorted(set(repos)),
        "models": sorted(set(models))[:20],  # cap at 20
        "services": sorted(set(services)),
        "widgets": sorted(set(widgets))[:15],
        "test_files": test_files,
        "depends_on": sorted(imports),
    }


if __name__ == "__main__":
    import sys
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    out = generate(root)
    size = out.stat().st_size
    data = json.loads(out.read_text())
    print(f"Generated {out} ({size // 1024}KB)")
    print(f"  {data['_meta']['total_modules']} modules, {data['_meta']['total_files']} files")
